
# Base URL
@baseUrl = http://localhost:3000

### Root endpoint
GET {{baseUrl}}/


###
GET {{baseUrl}}/api


### Create a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "first_name": "Lucy",
  "last_name": "Njambi",
  "email": "lnyambura@gmail.com",
  "phone_number": "0711477634",
  "password":"123456789",
  "user_type":"customer"
  
}

### Admin Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json


{
  "email": "joshua@gmail.com",
  "password": "123456789"
}

### user login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "denis@gmail.com",
  "password": "password123"
}



### Update user
PUT http://localhost:3000/api/users/2
Content-Type: application/json

{
  "first_name": "denis",
  "last_name": "kathuri",
  "email": "denis@gmail.com",
  "phone_number": "0723356478",
  "password": "password123"
}

### Get user by ID
GET {{baseUrl}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJmaXJzdF9uYW1lIjoiSm9zaHVhIiwibGFzdF9uYW1lIjoiTmdpZ2kiLCJlbWFpbCI6Impvc2h1YUBnbWFpbC5jb20iLCJ1c2VyX3R5cGUiOiJhZG1pbiIsImlhdCI6MTc2NDU1OTc3MywiZXhwIjoxNzY0NTY2OTczfQ.mptVzKDKuoloU63mZeoPb76njE9MWwFZVPOpZ0oVTL0



### Delete user
DELETE {{baseUrl}}/api/users/5

###Vehicle Management
POST http://localhost:3000/api/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJmaXJzdF9uYW1lIjoiSm9zaHVhIiwibGFzdF9uYW1lIjoiTmdpZ2kiLCJlbWFpbCI6Impvc2h1YUBnbWFpbC5jb20iLCJ1c2VyX3R5cGUiOiJhZG1pbiIsImlhdCI6MTc2MzY0NDczMSwiZXhwIjoxNzYzNjQ4MzMxfQ.uwYqGndZmuoyRP9LCkZmENzAEOj5hNXZqatEoil8a-E


{
  "rental_rate": 50.00,
  "current_location": "Westlands",
  "manufacturer": "Toyota",
  "model": "Camry",
  "year": 2023,
  "fuel_type": "Petrol",
  "engine_capacity": 2.5,
  "transmission": "Automatic",
  "seating_capacity": 5,
  "color": "White",
  "features": "AC, Bluetooth, Navigation",
  "vehicle_type": "four-wheeler"
}

### PAYMENT ENDPOINTS
POST {{baseUrl}}/api/payments/create-intent
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJmaXJzdF9uYW1lIjoiZGVuaXMiLCJsYXN0X25hbWUiOiJrYXRodXJpIiwiZW1haWwiOiJkZW5pc0BnbWFpbC5jb20iLCJ1c2VyX3R5cGUiOiJjdXN0b21lciIsImlhdCI6MTc2MzY5ODA2NSwiZXhwIjoxNzYzNzAxNjY1fQ.QdBTEKwewmITWG-z9G_Jw31XEMlkV-WJxj0kxXYP-38

{
  "booking_id": 1,
  "amount": 150.00
}